<?php
/**
 * @file
 * Displays Morphbank images on species pages; images come from
 * queries based on the taxonomic name for the given species page.
 */

// TODO: see module_load_include in eolapi.ajax.inc
require_once(drupal_get_path('module', 'morphbank') . '/morphbank.inc');

//define("MORPHBANK_SERVICE_REQUEST", "http://services.morphbank.net/mb3/request");
//define("MORPHBANK_NET_URL", "http://morphbank.net/");
//define("MORPHBANK_IMAGE_URL", "http://images.morphbank.net/");

/**
 * Implements hook_menu().
 *
 * @return multitype:string multitype:string
 */
function morphbank_menu(){
  $items['morphbank'] = array(
    'title' => 'Morphbank Callback',
    'description' => 'Endpoint to enable dynamic creation of Morphbank content.', //TODO: replace
    'page callback' => 'morphbank_callback',
    'file' => 'morphbank.ajax.inc',
    'access arguments' => array(
      'access content'
    ),
    'type' => MENU_CALLBACK
  );
  return $items;
}

/**
 * Callback to morphbank_search; called by morphbank_views_default_views ?
 *
 * @return multitype:string
 */
function morphbank_callbacks(){
  return array(
    'morphbank_images' => 'morphbank_search'
  );
}


/**
 * Use $tid to perform morphbank query.
 *
 * @param int $tid
 *   Term id of the current species page (taxonomy term page)
 * @param int $age
 *   Number of seconds in one week
 *   @todo: use or remove?
 */
function morphbank_search($tid, $age = 604800) {
  //TODO: return some content here?
  $term = taxonomy_term_load($tid);
  $term_name = $term->name;
  return array(
      'markup' => array(
          '#markup' => "<p>This should be a term name: {$term_name}</p>"
          ),
      );

}

/**
 * Implements hook_views_api().
 */
function morphbank_views_api(){
  return array(
    'api' => '3',
    'path' => drupal_get_path('module', 'morphbank') . '/views'
  );
}

/**
 * Implements hook_context_load_alter().
 *
 * Alters context so this module can add content
 *
 * This is where the location (on species_media, or taxonomy term, pages)
 * is dictated
 *
 * @param array $context
 */
function morphbank_context_load_alter(&$context){
  if($context->name === 'species_media' && isset($context->reactions['block'])){
    $context->reactions['block']['blocks']['views-morphbank_images-block'] = array(
      'module' => 'views',
      'delta' => 'morphbank_images-block',
      'region' => 'content',
      'weight' => '10'
    );
  }
}

/**
 * Provide image and link for footer.
 *
 * @param array $links
 */
function morphbank_footer_logos_alter(&$links){
  $options = array(
    'html' => true,
    'absolute' => true
  );
  $links[] = l(theme('image', array(
    'path' => drupal_get_path('module', 'morphbank') . '/images/mbLogoHeader.png',
    'alt' => 'Morphbank logo',
    'title' => 'Morphbank'
  )), 'http://www.morphbank.net/', $options);
}

